###OBTENER TODOS LOS USUARIOS
GET http://localhost:8080/api/users
###OBTENER UN USUARIO
GET http://localhost:8080/api/users/VvT1-knoS9-m0oSLo-mKp4N-T69a
###CREAR UN USUARIO
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "userName": "un fan d la beriso",
    "userEmail": "soyputo@gmail.com",
    "userDni": "numeriots",
    "userPhone": "3407-me la como",
    "totalReserves": 0
}
###MODIFICAR UN USUARIO
PATCH  http://localhost:8080/api/users/VvT1-knoS9-m0oSLo-mKp4N-T69a
Content-Type: application/json

{
    "userDni": "35418920",
    "userPhone": "3407412074"
}
###ELIMINAR UN USUARIO
DELETE http://localhost:8080/api/users/34c481ad-fa02-4631-b10e-a2f3c137b455