###OBTENER TODOS LOS USUARIOS
GET http://localhost:8080/api/users
###OBTENER UN USUARIO
GET http://localhost:8080/api/users/
###CREAR UN USUARIO
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "userName": "un fan d la beriso",
    "userEmail": "soyputo@gmail.com",
    "userDni": "numeriots",
    "userPhone": "3407-me la como",
    "totalReserves": 0
}
###MODIFICAR UN USUARIO
PATCH  http://localhost:8080/api/users/c15dd914-9494-441f-b340-9fe9a7cf3cad
Content-Type: application/json

{
    "userDni": "35418920",
    "userPhone": "3407412074"
}
###ELIMINAR UN USUARIO
DELETE http://localhost:8080/api/users/5780a683-66bb-4597-b056-055b336029ca