###OBTENER TODAS LAS FACTURAS
GET http://localhost:8080/api/receipts
###OBTENER UNA FACTURA
GET http://localhost:8080/api/receipts/6531916fa3467cdfcf5c0c2e
###CREAR UNA FACTURA
POST http://localhost:8080/api/receipts
Content-Type: application/json

{
    "registeredName": "La yegua de tu hermana",
    "receiptNumber": 1694,
    "amount": 4923.29,
    "paymentMethod": "una tirada de goma de tu vieja",
    "receiptType": "A"
}
###MODIFICAR UNA FACTURA
PATCH  http://localhost:8080/api/receipts/653190d3a3467cdfcf5c0c2d
Content-Type: application/json

{
    "registeredName": "Kevin Lonzo",
    "paymentMethod": "VISA"
}
###ELIMINAR UNA FACTURA
DELETE http://localhost:8080/api/receipts/6531916fa3467cdfcf5c0c2e