###OBTENER TODAS LAS FACTURAS
GET http://localhost:8080/api/receipts
###OBTENER UNA FACTURA
GET http://localhost:8080/api/receipts/FOIPI4-JShI-e59v-vA6Gm-OjmJ5
###CREAR UNA FACTURA
POST http://localhost:8080/api/receipts
Content-Type: application/json

{
    "registeredName": "La puta de tu vieja",
    "receiptNumber": 69,
    "amount": 44477.69,
    "paymentMethod": "tu hermana en 4",
    "receiptType": "A"
}
###MODIFICAR UNA FACTURA
PATCH  http://localhost:8080/api/receipts/FOIPI4-JShI-e59v-vA6Gm-OjmJ5
Content-Type: application/json

{
    "registeredName": "Cristian Alvarez"
}
###ELIMINAR UNA FACTURA
DELETE http://localhost:8080/api/receipts/27a5d09f-806f-4fa0-9532-75a3b00de911