###OBTENER TODAS LAS CANCHAS
GET http://localhost:8080/api/fields
###OBTENER UNA CANCHA
GET http://localhost:8080/api/fields/6524c7e723b6b4aab148f7bf
###CREAR UNA CANCHA
POST http://localhost:8080/api/fields
Content-Type: application/json

{
    "maxPlayers": 22,
    "fieldDimentions": "re grande tiene que ser",
    "avaible": true,
    "grassType": "Potrero"
}
###MODIFICAR UNA CANCHA
PATCH  http://localhost:8080/api/fields/6524c883ce565e23a26d9e45
Content-Type: application/json

{
    "fieldDimentions": "30x90",
    "avaible": false,
    "grassType": "Natural"
}
###ELIMINAR UNA CANCHA
DELETE http://localhost:8080/api/fields/6524c8ea10b08593eb624cea