###OBTENER TODAS LAS CANCHAS
GET http://localhost:8080/api/fields
###OBTENER UNA CANCHA
GET http://localhost:8080/api/fields/65318feea3467cdfcf5c0c29
###CREAR UNA CANCHA
POST http://localhost:8080/api/fields
Content-Type: application/json

{
    "maxPlayers": 22,
    "fieldDimentions": "re grande tiene que ser",
    "avaible": true,
    "grassType": "Potrero"
}
###MODIFICAR UNA CANCHA
PATCH  http://localhost:8080/api/fields/65318feea3467cdfcf5c0c29
Content-Type: application/json

{
    "fieldDimentions": "30x90",
    "avaible": false,
    "grassType": "Natural"
}
###ELIMINAR UNA CANCHA
DELETE http://localhost:8080/api/fields/65319003a3467cdfcf5c0c2a