###OBTENER TODAS LAS CANCHAS
GET http://localhost:8080/api/fields
###OBTENER UNA CANCHA
GET http://localhost:8080/api/fields/BQB4oJhe-2ig5-2oTX-mGMl-pIz5
###CREAR UNA CANCHA
POST http://localhost:8080/api/fields
Content-Type: application/json

{
    "maxPlayers": 6,
    "fieldDimentions": "12x18",
    "avaible": true,
    "grassType": "Sintetico"
}
###MODIFICAR UNA CANCHA
PATCH  http://localhost:8080/api/fields/2962142e-3599-4855-a659-e529c242542f
Content-Type: application/json

{
    "fieldDimentions": "12x16",
    "avaible": false,
    "grassType": "Natural"
}
###ELIMINAR UNA CANCHA
DELETE http://localhost:8080/api/fields/5c0d29ca-5438-413b-9bb7-314d4dac696d