###OBTENEER TODAS LAS PARRILLAS
GET http://localhost:8080/api/grills
###OBTENER UNA PARRILLA
GET http://localhost:8080/api/grills/652545abbe7529a5d700869b
###CREAR UNA PARRILLA
POST http://localhost:8080/api/grills
Content-Type: application/json

{
    "avaible": true,
    "grillDimentions": "chiquita",
    "grillType": "para homosexuales"
}
###MODIFICAR UNA PARRILA
PATCH  http://localhost:8080/api/grills/652545abbe7529a5d700869b
Content-Type: application/json

{
    "grillDimentions": "4x8",
    "grillType": "es a gas"
}
###ELIMINAR UNA PARRILLA
DELETE http://localhost:8080/api/grills/652545e9be7529a5d700869d