###OBTENEER TODAS LAS PARRILLAS
GET http://localhost:8080/api/grills
###OBTENER UNA PARRILLA
GET http://localhost:8080/api/grills/ZhHpT-xTXQD-gixhh-hifm-uSC6G
###CREAR UNA PARRILLA
POST http://localhost:8080/api/grills
Content-Type: application/json

{
    "avaible": true,
    "grillDimentions": "re grande",
    "grillType": "para mujeres"
}
###MODIFICAR UNA PARRILA
PATCH  http://localhost:8080/api/grills/06aaf94e-f247-4de6-8f77-9f07ce1b8ffe
Content-Type: application/json

{
    "grillDimentions": "maso grande",
    "grillType": "para todes"
}
###ELIMINAR UNA PARRILLA
DELETE http://localhost:8080/api/grills/fef1008a-35ca-4342-8ac2-d5db24f7e907