###OBTENEER TODAS LAS PARRILLAS
GET http://localhost:8080/api/grills
###OBTENER UNA PARRILLA
GET http://localhost:8080/api/grills/ae7834e3-57cf-49de-b6d2-c0e6fabad1e5
###CREAR UNA PARRILLA
POST http://localhost:8080/api/grills
Content-Type: application/json

{
    "avaible": true,
    "grillDimentions": "re grande",
    "grillType": "para mujeres"
}
###MODIFICAR UNA PARRILA
PUT http://localhost:8080/api/grills/ae7834e3-57cf-49de-b6d2-c0e6fabad1e5
Content-Type: application/json

{
        "avaible": true,
    "grillDimentions": "maso grande",
    "grillType": "para mujeres"
}
###ELIMINAR UNA PARRILLA
DELETE http://localhost:8080/api/grills/ae7834e3-57cf-49de-b6d2-c0e6fabad1e5