###OBTENER INFO
GET http://localhost:8080/api/employees
###CREAR INFO
POST http://localhost:8080/api/employees
Content-Type: application/json

{
    "employeeName": "qcyo",
    "employeeEmail": "qcyo@gmail.com",
    "employeeCuil": "numeritos",
    "age": 12,
    "ancient": 6,
    "employeeStatus": true
}
###OBTENER INFO DE UNA ID
GET http://localhost:8080/api/employees/a02b91bc-3769-4221-beb1-d7a3aeba7dad
###MODIFICAR INFO DE UNA ID
PUT http://localhost:8080/api/employees/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
    "employeeName": "Maximo Meridio",
    "employeeEmail": "maxid10@gmail.com",
    "employeeCuil": "18-7342829-7",
    "age": 36,
    "ancient": 6,
    "employeeStatus": true
}
###BORRAR INFO
DELETE http://localhost:8080/api/employees/7547d346-a33f-498f-9d0a-a84c034a2067