###OBTENER INFO
GET http://localhost:8080/api/employees
###CREAR INFO
POST http://localhost:8080/api/employees
Content-Type: application/json

{
    "employeeName": "qcyo",
    "employeeEmail": "qcyo@gmail.com",
    "employeeCuil": "numeritos",
    "age": 12,
    "ancient": 6,
    "employeeStatus": true
}
###OBTENER INFO DE UNA ID
GET http://localhost:8080/api/employees/a02b91bc-3769-4221-beb1-d7a3aeba7dad
###MODIFICAR INFO DE UNA ID
PATCH  http://localhost:8080/api/employees/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
    "employeeName": "Pepe Juanez",
    "employeeEmail": "pepijnz@gmail.com",
    "employeeCuil": "18-44514687-7"
}
###BORRAR INFO
DELETE http://localhost:8080/api/employees/d8a4cdff-4618-4d0d-a5c0-08dd29110ef0