###OBTENER INFO
GET http://localhost:8080/api/employees
###CREAR INFO
POST http://localhost:8080/api/employees
Content-Type: application/json

{
    "employeeName": "soy de boca",
    "employeeEmail": "tengofrio@gmail.com",
    "employeeCuil": "22-bosta-0",
    "age": 15,
    "ancient": 3,
    "employeeStatus": true
}
###OBTENER INFO DE UNA ID
GET http://localhost:8080/api/employees/6525fc05f4ee79d628951e9c
###MODIFICAR INFO DE UNA ID
PATCH  http://localhost:8080/api/employees/65318fb3a3467cdfcf5c0c27
Content-Type: application/json

{
    "employeeName": "Franco Swarchz",
    "employeeCuil": 22,
    "age": 22,
    "ancient": 0
}
###BORRAR INFO
DELETE http://localhost:8080/api/employees/65318fc7a3467cdfcf5c0c28